# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190531_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='workoutlog',
            field=models.ForeignKey(blank=True, help_text='this shows what log belongs to which session or otherwise', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutLog', verbose_name='workoutlog'),
        ),
    ]
